#ifndef ENUMGAME_H
#define ENUMGAME_H

enum GameGamestate
{

    GAMEMODE, TITLEMODE, MAPMODE, TELEPORTERMODE, GAMECOMPLETE,  GAMECOMPLETE2, EDITORMODE, PRELOADER, CONNECTINGMODE, SERVERMODE

};

#endif /* ENUMGAME_H */
