name: CI-loc

# Trigger on every push and pull request.
# Different from upstream as artifacts are created.
on: [push, pull_request]

env:
  SRC_DIR_PATH: desktop_version

jobs:
  zip:
    name: Zip

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: false

    - name: Upload fonts
      uses: actions/upload-artifact@v4
      with:
        name: fonts
        path: ${{ env.SRC_DIR_PATH }}/fonts/

    - name: Upload lang
      uses: actions/upload-artifact@v4
      with:
        name: lang
        path: ${{ env.SRC_DIR_PATH }}/lang/
